In [678]:
import pandas as pd
import matplotlib.pyplot as plt
#import seaborn as sns
import numpy as np
import streamlit as slt

print('read')

read

In [679]:
df = pd.read_csv("incidents (1) python project.csv")

In [680]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7500 non-null   object
 1   Title             7500 non-null   object
 2   Start date        7500 non-null   object
 3   End date          7500 non-null   object
 4   Number of deaths  7500 non-null   int64
dtypes: int64(1), object(4)
memory usage: 293.1+ KB

In [681]:
df.head(3)

  Identifier                   Title  Start date    End date  Number of deaths
0  IBD031681     Food Poisoning, Imo  18/04/2025  18/04/2025                 1
1  IBD032064  Gunmen Kill Man, Benue  31/03/2025  31/03/2025                 1
2  IBD032058       Auto Crash, Lagos  31/03/2025  31/03/2025                 1

In [682]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7500 non-null   object
 1   Title             7500 non-null   object
 2   Start date        7500 non-null   object
 3   End date          7500 non-null   object
 4   Number of deaths  7500 non-null   int64
dtypes: int64(1), object(4)
memory usage: 293.1+ KB

In [683]:
df = df.drop_duplicates()
df

,Identifier,Title,Start date,End date,Number of deaths
0,IBD031681,"Food Poisoning, Imo",18/04/2025,18/04/2025,1
1,IBD032064,"Gunmen Kill Man, Benue",31/03/2025,31/03/2025,1
2,IBD032058,"Auto Crash, Lagos",31/03/2025,31/03/2025,1
3,IBD032066,"Stray Bullets, Sokoto",31/03/2025,31/03/2025,1
4,IBD032062,"Lightening Kills Herder, Kaduna",30/03/2025,30/03/2025,1
...,...,...,...,...,...
7495,IBD024354,"Auto Crash, Niger",18/06/2022,18/06/2022,18
7496,IBD024357,"Boat Mishap, Bayelsa",18/06/2022,18/06/2022,7
7497,IBD024385,"Fulani Herdsmen and Youths, Abia",18/06/2022,18/06/2022,3
7498,IBD024352,"Mob vs Phone Thief, Bayelsa",18/06/2022,18/06/2022,1
7499,IBD024344,"Herdsmen Attack, Benue",17/06/2022,17/06/2022,2

In [684]:
df[["Incident","State"]] = df["Title"].str.split(",", n=1, expand=True)
#df[["Incident","State"]] = df["Title"].str.split(",", n=1, expand=True)

In [685]:
df

,Identifier,Title,Start date,End date,Number of deaths,Incident,State
0,IBD031681,"Food Poisoning, Imo",18/04/2025,18/04/2025,1,Food Poisoning,Imo
1,IBD032064,"Gunmen Kill Man, Benue",31/03/2025,31/03/2025,1,Gunmen Kill Man,Benue
2,IBD032058,"Auto Crash, Lagos",31/03/2025,31/03/2025,1,Auto Crash,Lagos
3,IBD032066,"Stray Bullets, Sokoto",31/03/2025,31/03/2025,1,Stray Bullets,Sokoto
4,IBD032062,"Lightening Kills Herder, Kaduna",30/03/2025,30/03/2025,1,Lightening Kills Herder,Kaduna
...,...,...,...,...,...,...,...
7495,IBD024354,"Auto Crash, Niger",18/06/2022,18/06/2022,18,Auto Crash,Niger
7496,IBD024357,"Boat Mishap, Bayelsa",18/06/2022,18/06/2022,7,Boat Mishap,Bayelsa
7497,IBD024385,"Fulani Herdsmen and Youths, Abia",18/06/2022,18/06/2022,3,Fulani Herdsmen and Youths,Abia
7498,IBD024352,"Mob vs Phone Thief, Bayelsa",18/06/2022,18/06/2022,1,Mob vs Phone Thief,Bayelsa
7499,IBD024344,"Herdsmen Attack, Benue",17/06/2022,17/06/2022,2,Herdsmen Attack,Benue

In [686]:
df.isna().sum()

Identifier           0
Title                0
Start date           0
End date             0
Number of deaths     0
Incident             0
State               17
dtype: int64

In [687]:
df = df.drop_duplicates()

In [688]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7485 entries, 0 to 7499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7485 non-null   object
 1   Title             7485 non-null   object
 2   Start date        7485 non-null   object
 3   End date          7485 non-null   object
 4   Number of deaths  7485 non-null   int64
 5   Incident          7485 non-null   object
 6   State             7468 non-null   object
dtypes: int64(1), object(6)
memory usage: 467.8+ KB

In [689]:
df

,Identifier,Title,Start date,End date,Number of deaths,Incident,State
0,IBD031681,"Food Poisoning, Imo",18/04/2025,18/04/2025,1,Food Poisoning,Imo
1,IBD032064,"Gunmen Kill Man, Benue",31/03/2025,31/03/2025,1,Gunmen Kill Man,Benue
2,IBD032058,"Auto Crash, Lagos",31/03/2025,31/03/2025,1,Auto Crash,Lagos
3,IBD032066,"Stray Bullets, Sokoto",31/03/2025,31/03/2025,1,Stray Bullets,Sokoto
4,IBD032062,"Lightening Kills Herder, Kaduna",30/03/2025,30/03/2025,1,Lightening Kills Herder,Kaduna
...,...,...,...,...,...,...,...
7495,IBD024354,"Auto Crash, Niger",18/06/2022,18/06/2022,18,Auto Crash,Niger
7496,IBD024357,"Boat Mishap, Bayelsa",18/06/2022,18/06/2022,7,Boat Mishap,Bayelsa
7497,IBD024385,"Fulani Herdsmen and Youths, Abia",18/06/2022,18/06/2022,3,Fulani Herdsmen and Youths,Abia
7498,IBD024352,"Mob vs Phone Thief, Bayelsa",18/06/2022,18/06/2022,1,Mob vs Phone Thief,Bayelsa
7499,IBD024344,"Herdsmen Attack, Benue",17/06/2022,17/06/2022,2,Herdsmen Attack,Benue

In [690]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7485 entries, 0 to 7499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7485 non-null   object
 1   Title             7485 non-null   object
 2   Start date        7485 non-null   object
 3   End date          7485 non-null   object
 4   Number of deaths  7485 non-null   int64
 5   Incident          7485 non-null   object
 6   State             7468 non-null   object
dtypes: int64(1), object(6)
memory usage: 467.8+ KB

In [691]:

df = df.drop(columns=['Title'])

In [692]:
df.head(3)

,Identifier,Start date,End date,Number of deaths,Incident,State
0,IBD031681,18/04/2025,18/04/2025,1,Food Poisoning,Imo
1,IBD032064,31/03/2025,31/03/2025,1,Gunmen Kill Man,Benue
2,IBD032058,31/03/2025,31/03/2025,1,Auto Crash,Lagos

In [693]:
df["State"] = df["State"].str.strip()

In [694]:
df

,Identifier,Start date,End date,Number of deaths,Incident,State
0,IBD031681,18/04/2025,18/04/2025,1,Food Poisoning,Imo
1,IBD032064,31/03/2025,31/03/2025,1,Gunmen Kill Man,Benue
2,IBD032058,31/03/2025,31/03/2025,1,Auto Crash,Lagos
3,IBD032066,31/03/2025,31/03/2025,1,Stray Bullets,Sokoto
4,IBD032062,30/03/2025,30/03/2025,1,Lightening Kills Herder,Kaduna
...,...,...,...,...,...,...
7495,IBD024354,18/06/2022,18/06/2022,18,Auto Crash,Niger
7496,IBD024357,18/06/2022,18/06/2022,7,Boat Mishap,Bayelsa
7497,IBD024385,18/06/2022,18/06/2022,3,Fulani Herdsmen and Youths,Abia
7498,IBD024352,18/06/2022,18/06/2022,1,Mob vs Phone Thief,Bayelsa
7499,IBD024344,17/06/2022,17/06/2022,2,Herdsmen Attack,Benue

In [695]:
replace_map ={
    60:"Imo",78:"Benue",171:"Edo",330:"Imo",837:"Delta",
    857:"Edo",858:"Lagos",865:"Kastina",1768:"(FCT) Abuja",1800:"(FCT)Abuja",2318:"(FCT)Abuja",
    2875:"Akwa Ibom",2889:"Delta2",3888:"Edo",5182:"(FCT)Abuja",6049:"Jigawa",
    6136:"Kaduna",6321:"Lagos",2932:"(FCT) Abuja",6884:"Edo"}

In [696]:
for idx , val in replace_map.items():
    if pd.isna(df.loc[idx, "State"]) or df.loc[idx, "State"].strip() == "":
        df.loc[idx, "State"] =val

In [697]:
aso = ['FCT','FCT (Abuja)','FCT, Abuja','FCT, (Abuja)','FCT(Abuja)', 'Abuja', 'FCT ( Abuja)',
'Hamza Musa', 'Vigilantes vs Herders, FCT (Abuja)','Abuja (FCT)','(fct) Abuja','FCT, ( Abuja)','(FCT)Abuja',
]

mask = df['State'].isin(aso)
df.loc[mask,'State'] = '(FCT) Abuja'

In [698]:
# 📝 Clean and standardize State names by correcting typos, removing variations, 
# and replacing inconsistent entries with their proper names

df['State'] = df['State'].replace(['Rivers (Offshore)','Port Harcourt','Bonny','River'], 'Rivers')
df['State'] = df['State'].replace('Bayelsa (Offshore)', 'Bayelsa')
df['State'] = df['State'].replace('Son, Anambra', 'Anambra')
df['State'] = df['State'].replace('Dies, Ogun', 'Ogun')
df['State'] = df['State'].replace(['Worshipper, Delta', 'n','delta'], 'Delta')
df['State'] = df['State'].replace(['Akwa Ibom (Offshore)', 'Uyo','Akwa Ibom'], 'Akwa Ibom')
df['State'] = df['State'].replace('Ondo, Ondo', 'Ondo')
df['State'] = df['State'].replace(['Katsina 2','Katsina 1',' Katisna','Katisna','Katsina'], 'Katsina')
df['State'] = df['State'].replace(['Nasarwa', 'Nasaraawa'], 'Nasarawa')
df['State'] = df['State'].replace('Bornon', 'Borno')
df['State'] = df['State'].replace(['Jigaawa','Jiagawa','Jigiwa'], 'Jigawa')
df['State'] = df['State'].replace(['Kadauna','Kadun','kaduna'], 'Kaduna')
df['State'] = df['State'].replace(['Anmabra','ANambra'], 'Anambra')
df['State'] = df['State'].replace('Taraba`', 'Taraba')
df['State'] = df['State'].replace(['Katisna','Kastina', 'katisna'], 'Katsina')
df['State'] = df['State'].replace('Zamafara', 'Zamfara')
df['State'] = df['State'].replace('Cross RIvers', 'Cross River')
df['State'] = df['State'].replace('Niger State', 'Niger')
df['State'] = df['State'].replace('Delta2','Delta')
df['State'] = df['State'].replace('bauchi','Bauchi')
df['State'] = df['State'].replace('kwara','Kwara')
df['State'] = df['State'].replace('kano','Kano')
df['State'] = df['State'].replace('kogi','Kogi')
df['State'] = df['State'].replace('Akwa ibom','Akwa Ibom')
df['State'] = df['State'].replace('RIvers','Rivers')
#df['State'] = df['State'].replace('kano','Kano')
#df['State'] = df['State'].replace('kano','Kano')

In [699]:
df.loc[60, "Incident"] = df.loc[60, "Incident"].replace(". Delta", "").strip()
df.loc[78, "Incident"] = df.loc[78, "Incident"].replace(" Benue", "").strip()
df.loc[171, "Incident"] = df.loc[171, "Incident"].replace(" Edo", "").strip()
df.loc[3888, "Incident"] = df.loc[388, "Incident"].replace(". Edo", "").strip()
df.loc[1768, "Incident"] = df.loc[1768, "Incident"].replace(" FCT (Abuja)", "").strip()
df.loc[6049, "Incident"] = df.loc[6049, "Incident"].replace(" Jigawa", "").strip()

In [700]:
#convert Start Date and End date columns to dateline format 
df['Start date'] = pd.to_datetime(df['Start date'],format='mixed', errors='coerce')
df['End date'] = pd.to_datetime(df['End date'],format='mixed', errors='coerce')

In [701]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7485 entries, 0 to 7499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7485 non-null   object
 1   Start date        7484 non-null   datetime64[ns]
 2   End date          7484 non-null   datetime64[ns]
 3   Number of deaths  7485 non-null   int64
 4   Incident          7485 non-null   object
 5   State             7485 non-null   object
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 667.4+ KB

In [705]:
asf = df['State'].nunique()
print(asf, "States")

37 States

In [703]:
value_counts = df['State'].value_counts()
unique_values = value_counts[value_counts == 10].index

print(unique_values.tolist())

[]

In [704]:
df.to_csv('jemilat.csv')